# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Irvanjit Singh
tagline:
description:
url:                 http://irvanjit.com
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              Irvanjit Singh Gill
  url:               https://irvanjit.com
  email:             contact@irvanjit.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
