# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Irvanjit Singh
tagline:
description:
url:                 http://irvanjit.com
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              Irvanjit Singh
  url:               https://irvanjit.com
  email:             me@irvanjit.com
  twitter:           irvanjit
  github:            irvanjit
  stackoverflow:     irvanjit
  linkedin:          irvanjit

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]

theme: minimal-mistakes-jekyll
